name: "Test"
description: "Test calling peter-evans/create-pull-request as an action"

uns:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create blah.txt
      run: echo "This is some content" > blah.txt
      shell: bash
      working-directory: ${{ github.workspace }}
    - name: Create a PR for local changes
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "IGNORE THIS - TEST"
        title: "IGNORE THIS - TEST"
        body: "IGNORE THIS - TEST"
        branch: "ignore-this-branch-it-is-for-testing-only"
        delete-branch: true